---
- name: Preparation code of the day  -Task3
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Récupération du code wifi -Task3
      get_url:
        url: https://nemo-preprod.dc1.ext.agencedpc.fr/api/wifi-code
        dest: /opt/ansible/networking/code-wifi
      register: file_pass
    - name: Enregistrement  -Task3
      debug:
        msg: "{{ file_pass }}"
    - name: Préparation password  -Task3
      command: python3 /opt/ansible/networking/extractionCode.py
    - name: Affiche le mot de pass -Task3
      shell: cat /opt/ansible/networking/nemo/wifi_code.txt
      register: result
    - name: recupération du passord dans une variable -Task3
      set_fact:
        password: "{{ result.stdout }}"
    - name: creation de fichier avec ma variable  -Task3
      copy:
        content: | 
          ---
          pass: {{ password }}
        dest: /opt/ansible/networking/nemo/password.yml
    - name: Affichage du password  -Task3
      debug:
        msg: "{{ password }}"


